Migrating from React.PropTypes
JedWatson/react-hammerjs pull request #67
Opened 2017-04-16 20:23 UTC by chadams

using prop-types package for newer React version 15.5.0

2017-04-16 20:29 UTC, chadams commented
I went ahead and added both react updates to same branch as they were small

2017-04-17 11:35 UTC, afc163 commented
:+1:

2017-04-17 16:15 UTC, probablyup commented
@JedWatson without these changes, using the component with React >=15.5 emits red console errors that look like hard errors (thanks Facebook 😞); would be great to get this in soon

2017-04-27 05:47 UTC, afc163 commented
ping

2017-05-05 10:30 UTC, derpoho commented
@JedWatson Can you please merge this? Since the React 16 Update is coming soon, this is seriously necessary!

2017-05-05 10:49 UTC, derpoho requested changes

2017-05-05 10:49 UTC, derpoho commented on src/Hammer.js
> +    static propTypes = {
Setting Statics will not work with Webpack if someone doesn't compile the node_modules folder. For the sake of compatibility you need to add PropTypes and displayName after instantiating the class:

```
HammerComponent.displayName = 'Hammer'
HammerComponent.propTypes = {
	className: PropTypes.string,
}
```

2017-05-05 10:49 UTC, derpoho commented on src/Hammer.js
Here:
```
HammerComponent.displayName = 'Hammer'
HammerComponent.propTypes = {
	className: PropTypes.string,
}
```

2017-05-05 10:50 UTC, derpoho commented
@chadams Maybe you can implement the suggested changes, then we could use this PR.

2017-05-10 07:06 UTC, paranoidjk commented
@derpoho can you merge this and continue fix the suggested changes, since we need to fix the react warning.

2017-05-10 07:06 UTC, paranoidjk commented
@derpoho or i can open a another PR after you merge this

2017-05-10 07:08 UTC, derpoho commented
@paranoidjk I can't merge it, i have no rights in this Repo, you must ask @chadams ;)

2017-05-10 07:11 UTC, afc163 commented
I don't think this is still maintained, maybe we should maintain a forked version? @paranoidjk

2017-05-10 07:17 UTC, paranoidjk commented
@afc163 

Ok, i will fork this repo to [react-component](https://github.com/react-component/) group and continue to mantain it.

still, thanks for @JedWatson great job.

2017-05-14 12:32 UTC, JedWatson requested changes
Thanks for the PR! would you mind fixing these two things please? then I can merge it and publish a new version

2017-05-14 12:32 UTC, JedWatson commented on src/Hammer.js
> +class HammerComponent extends React.Component {
We're not using babel, so using the new class syntax will break browser support. We need to use the `create-react-class` package instead and leave this as-is

2017-05-14 12:32 UTC, JedWatson commented on package.json
> +    "prop-types": "^15.5.8",
this should be added as a dependency, otherwise projects depending on `react-hammerjs` won't have it installed

2017-05-14 13:06 UTC, JedWatson commented
Just FYI - I've been away for personal reasons but am picking this up at the moment and getting it ready for react 16, plus merging some other fixes.

@afc163 @paranoidjk I don't mind if you want to continue to maintain a fork, but you're welcome to help maintain this one if you like, just let me know.

2017-05-25 23:11 UTC, pista329 commented
Any progress on this guys?

2017-05-26 02:38 UTC, paranoidjk commented
@JedWatson 💯 
Since our project https://ant.design/ is heavily rely on hammerjs, so  I'd like to help with mantain this one.

If you agree with this, please add me owner permission,  both my github and npm id is `paranoidjk`, email is `hust2012jiangkai@gmail.com`, thanks.

> our fork is https://github.com/react-component/react-hammerjs

2017-05-29 10:24 UTC, ibc commented
@JedWatson, I do not mean to hurry but any idea when this PR will be merged and a new NPM version will be available?

2017-06-01 15:11 UTC, chadams commented
Sorry missed these comments. However, I'm not understanding what needs to be done.

2017-06-02 13:21 UTC, pista329 commented
Hey guys, this should do the work. https://github.com/JedWatson/react-hammerjs/pull/74

2017-06-03 20:02 UTC, chadams commented
I removed the statics, is thats what is holding this up?

2017-06-04 01:10 UTC, chadams commented on src/Hammer.js
> +class HammerComponent extends React.Component {
Done, are there any official tests for hammer, or some good place to test this change?

2017-06-14 12:48 UTC, quantumew commented
I can't use this wonderful tool in prod if it takes months to get fixes like these in. Perhaps another owner/maintainer should be added to this project. It is a pity because this tool is so easy.

2017-08-04 10:56 UTC, wwqrd commented
@chadams Did you ever find out?

2017-08-07 20:33 UTC, jrsinclair commented
If I understand correctly, what's holding this up is that `prop-types` needs to be moved in package.json from `devDependencies` to `dependencies`. Can anyone confirm this?

2017-08-24 19:33 UTC, synaestheory commented
@chadams @jrsinclair The move from devDependencies to dependencies is the only comment on the PR where changes were requested.  I would guess that's all that's holding this up.

2017-08-25 10:03 UTC, wwqrd commented
Looks like a version with the amends has already been posted here: #74

2017-09-27 22:57 UTC, jrsinclair commented
This just became slightly more pressing, now that React 16 has been released.

2017-10-17 23:02 UTC, jrsinclair commented
Was this PR made redundant by #78?

2017-10-24 13:36 UTC, JedWatson commented
There were a bunch of issues with this in the end, I've cleaned it up significantly and replaced the build system so it should be good now. Try using `1.0.1`

2017-10-24 13:36 UTC, closed without merging